[project]
<<<<<<< HEAD
name = "atlassian-mcp-client"
=======
name = "atlassian-mcp-server"
>>>>>>> 31fd4a8afde5492d35184533818f61ea42a4fca8
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
<<<<<<< HEAD
dependencies = []
=======
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.10.1",
]
>>>>>>> 31fd4a8afde5492d35184533818f61ea42a4fca8
